runtime: python
env: flex
entrypoint: gunicorn -b :$PORT item_catalog:app
threadsafe: true
manual_scaling:
  instances: 1
runtime_config:
  python_version: 2

handlers:
- url: /static
  static_dir: static

- url: /static/photos
  static_dir: static/photos

- url: /.*
  script: item_catalog.app